# Generated by Django 6.0.5 on 2026-05-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=100)),
                ('weightage', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='co',
            old_name='co_code',
            new_name='co_number',
        ),
        migrations.RenameField(
            model_name='copomapping',
            old_name='mapping_strength',
            new_name='mapping_level',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='department',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='po',
            old_name='po_code',
            new_name='po_number',
        ),
        migrations.RemoveField(
            model_name='co',
            name='blooms_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='regulation',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='po',
            name='gapc',
        ),
        migrations.RemoveField(
            model_name='po',
            name='sdg',
        ),
        migrations.RemoveField(
            model_name='po',
            name='wk',
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('max_marks', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.assessment')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.co')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
