# Generated by Django

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('attainment', '0004_student_studentmark'),
    ]
    operations = [
        migrations.CreateModel(
            name='COAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_percentage', models.FloatField()),
                ('attainment_score', models.FloatField()),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attainment.co')),
            ],
        ),
    ]